server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myboard?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: boarduser
    password: xnths8686
  # --- ↓↓↓ 여기에 메일 설정 추가 ↓↓↓ ---
  mail:
    host: smtp.gmail.com  # 사용하려는 SMTP 서버 주소 (예: Gmail)
    port: 587
    username: mailserver7210@gmail.com
    password: vkmu qqcb opsk hsri
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*" 
  # --- ↑↑↑ 여기까지 추가 ---
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  type-handlers-package: com.example.demo.config
